### ISSUE TITLE
Redundance between api definition and response

### ISSUE THREAD

**Issue by AiyionPrime** [g3n35i5/shop-db2#11]
When an api user requests a resource, it does not get a user object as expected, but an object wrapping a user object, with the text identifier "user". Not only does this lack a purpose, as the requester already nows what he expects at request-time, but it complicates both your code as well as the code of external projects accessing the api, likely leading to bugs.

https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L123

This does not only apply to the user info but to all api paths in the file.

https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L36
https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L52
https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L70
https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L88
https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L106
https://github.com/g3n35i5/shop-db2/blob/c86cb2ef93a123952146fdc6e5dfef4c85df8024/shopdb/routes/users.py#L123

**Comment by g3n35i5** [comment]
Thanks @AiyionPrime for the hint. To be honest, this behavior of the API itself got on my nerves, but now that others seem to have a problem with it, I can take a look at it. You can expect an update soon.
